format = """
$username\
$hostname\
$directory\
$kubernetes\
$python\
$git_branch\
$git_state\
$git_status\
$sudo\
$jobs\
$cmd_duration\
$status\
$character"""


add_newline = false

[line_break]
disabled = true

[directory]
disabled = false
truncation_length = 5
truncate_to_repo = false

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[python]
disabled = false
detect_files = []
detect_extensions = []
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch)]($style) '

[sudo]
disabled = false
format = '[$symbol]($style) '

[status]
disabled = false


[cmd_duration]
disabled = false
format = '[$duration]($style) '
