format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$cmd_duration\
$status\
$character"""

add_newline = false

[line_break]
disabled = true

[username]
show_always = true

[status]
disabled = false
