#!/bin/sh
csum=""
new_csum=$(sha1sum $(which dwm))
sh /home/noppakorn/.dwm/autostart.sh > /home/noppakorn/.dwm/autostart.log
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        _JAVA_AWT_WM_NONREPARENTING=1 dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
